### ISSUE TITLE
[FEATURE] Ctrl + Q to Quit

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/journal#46] opened 2015-03-02 05:04 UTC
As per the subject :D

**Comment by ryanleesipes** [comment] 2015-03-02 14:42
Is this a shortcut in other editors?

**Comment by zesterer** [comment] 2015-03-02 17:52
As far as I'm aware, it is. If not, then it's a good one.

Although be careful. If Ctrl+W is close tab, then a tiny slip of they fingers can spell disaster :D

**Comment by ikeydoherty** [comment] 2015-03-02 18:44
ALT+F4? :)

**Comment by zesterer** [comment] 2015-03-02 18:53
Touché

**Comment by ryanleesipes** [comment] 2015-03-02 19:27
Actually what I was thinking (alt+F4). However, I may implement something for closing current tab and cycling through tabs.

**Comment by Justinzobel** [comment] 2015-03-02 21:11
Barry why did you just close this? Is it implemented?

Ryan it is a shortcut in Gedit and another though I can't remember what it
was.

Alt F4 is a bit A) more difficult and B) a Windows thing :P

**Comment by Justinzobel** [comment] 2015-03-02 21:12
Also being next to close tab isn't an issue, you can always re-open
Journal, and if the save-mechanism is working fine (ie not allowing a user
to close a tab that isn't saved without a prompt) I see no issues at all....

**Comment by ryanleesipes** [comment] 2015-03-02 21:45
Confirmed as a keyboard shortcut in Gedit. I will implement it.

**Comment by zesterer** [comment] 2015-03-02 22:42
To answer your question Justin, I was typing fast and pressed Tab to switch the the next element on the page, assuming it's be "comment". Turns out it was "close and comment"...

**Comment by Justinzobel** [comment] 2015-03-02 22:57
Heh github to the rescue! Bit of a crap tab order.

**Comment by ryanleesipes** [comment] 2015-05-25 17:49
This was taken care of by @michaelrutherford

**Closed by ryanleesipes** 2015-05-25 17:49 UTC
Labels: enhancement
